function [fitresult, gof] = createFit1(X, Y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Apr-2020 02:07:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'A + K / (sqrt(x) + B)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.319123608916665 0.426335503745881 0.244857096797395];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData,'ok','MarkerSize',12,'MarkerFaceColor',[0 0 1] );
% legend( h, 'Data', 'Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'X', 'Interpreter', 'none' );
% ylabel( 'Y', 'Interpreter', 'none' );
% grid on


